after-startup-command = ['exec-and-forget ~/.config/aerspace/gap.sh', 'exec-and-forget sketchybar', 'exec-and-forget borders']

exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE'
]

start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.right = 6
outer.top = 40

[mode.main.binding]
cmd-r = 'mode resize'
cmd-shift-r = 'mode service'

cmd-b = "exec-and-forget /bin/bash -c '~/.config/sketchybar/plugins/toggle_bar.sh'"

cmd-slash = 'layout tiles horizontal vertical'

cmd-h = 'focus left'
cmd-j = 'focus down'
cmd-k = 'focus up'
cmd-l = 'focus right'

cmd-f = 'fullscreen'

cmd-shift-h = 'move left'
cmd-shift-j = 'move down'
cmd-shift-k = 'move up'
cmd-shift-l = 'move right'

cmd-1 = "workspace 1"
cmd-2 = "workspace 2"
cmd-3 = "workspace 3"
cmd-4 = "workspace 4"
cmd-5 = "workspace 5"
cmd-6 = "workspace 6"

cmd-shift-1 = "move-node-to-workspace 1"
cmd-shift-2 = "move-node-to-workspace 2"
cmd-shift-3 = "move-node-to-workspace 3"
cmd-shift-4 = "move-node-to-workspace 4"
cmd-shift-5 = "move-node-to-workspace 5"
cmd-shift-6 = "move-node-to-workspace 6"

[mode.resize.binding]
cmd-r = 'mode main'
enter = 'mode main'
esc = 'mode main'

minus = 'resize smart -50'
equal = 'resize smart +50'
h = 'resize width -50'
j = 'resize height -50'
k = 'resize height +50'
l = 'resize width +50'

[mode.service.binding]
esc = ['reload-config', 'mode main']
f = ['layout floating tiling', 'mode main']

backspace = ['close-all-windows-but-current', 'mode main']
cmd-g = ["exec-and-forget ~/.config/aerospace/toggle_top_gap.sh", "mode main"]

cmd-shift-h = ['join-with left', 'mode main']
cmd-shift-j = ['join-with down', 'mode main']
cmd-shift-k = ['join-with up', 'mode main']
cmd-shift-l = ['join-with right', 'mode main']
