set -s escape-time 0

unbind C-b
set -g prefix C-r

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"


bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top 

set -g base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'uhs-robert/tmux-oasis'

set -g @oasis_flavor "twilight"

# if-shell '[ -f ~/.tmux/themes/tmux-oasis/oasis_tmux.conf ]' \
#   'source-file ~/.tmux/themes/tmux-oasis/oasis_tmux.conf'

set-window-option -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

bind-key p display-popup -E '
selected=$(tmuxinator list -n | fzf)

[ -z "$selected" ] && exit

tmuxinator start "$selected"
'

bind-key X confirm-before -p "kill-session #S? (y/n)" kill-session

run '~/.tmux/plugins/tpm/tpm'
